### ISSUE TITLE
Support for Kodi 19 Matrix

### ISSUE THREAD

**Issue by zebbe152** [emilsvennesson/kodi-viaplay#44] opened 2021-02-22 14:36 UTC
Are there any plans to make this add-on compatible with Kodi 19 Matrix?

**Comment by SweXtal** [comment] 2021-02-23 16:47
There are a couple of issues. 

First, prior versions <19 used Python 2.x, where Kodi 19 uses Python 3.x. That's the "not compatible" issue.

In windows, you go to %USERPROFILE%\appdata\roaming\kodi\addons\plugin.video.viaplay

in addon.xml you have two choices what to do.
Fix A: 
edit the line containing "<import addon="xbmc.python" version="2.25.0" />" and replace 2.25.0 with 3.0.0 which is the Kodi 19 xbmc.python repo
Fix B:
Edit the line containing "<import addon="xbmc.python" version="2.25.0" />" and comment the whole line out so it reads
""

in directory %USERPROFILE%\appdata\roaming\kodi\addons\plugin.video.viaplay\resources\lib some things has changed and you have to do some editing there too.

edit the viaplay.py and:
* find the line "import cookielib" and change that line to read "import http.cookiejar as cookielib".
* find the line "import HTMLParser" and do either commend that line out completely with "## import HTMLParser" since it's built in OR replace it with "import html.parser as HTMLParser" (don't know which is best to do, other people can answer that).

I've coded Python for about one hour so this gives further errors but it seems more related to JSON.

**Comment by ravenrocks** [comment] 2021-02-26 14:15
Hi SweXtal.
Have you found a way to actually play videos in Matrix, the changes above makes it open fine and all, but not play anything.

**Comment by SweXtal** [comment] 2021-02-26 19:19
No. As I wrote, this was during my first ever experience of python. I'm a complete noob at this and I don't have time to become a superhero pythonist. It seems that between Kodi 18.x and 19x something also changed in the JSON. Hence the faults. I am NOT an experienced Python nor Kodi programmer. I just want to state that and make it clear. This is walking in a minefield for me....

**Comment by emilsvennesson** [comment] 2021-02-26 21:07
Duplicate of #41.

**Closed by emilsvennesson** 2021-02-26 21:07 UTC
