### ISSUE TITLE
No channels on no tv to go subscriptions

### ISSUE THREAD

**Issue by sebastiananad** [emilsvennesson/kodi-viaplay#21] opened 2018-05-13 06:33 UTC
I can see a listing of channels when i log in by desktop but not in kodi.

I attached a part of the json including the stream urls from desktop

/Sebastian

[partofjson.zip](https://github.com/emilsvennesson/kodi-viaplay/files/1998183/partofjson.zip)

**Comment by Zaccov** [comment] 2018-05-19 15:34
Hi I just tried a friends account. He has a Viaplay account thru his viasat subscription and there it works.
He has a Viasat account with Viaplay.
I have a regular Viaplay account and there it wont work.
Is there anything we can assist with so that it will work?

**Comment by emilsvennesson** [comment] 2018-05-23 18:49
Hi!

Can you please attach a Kodi debug log? It will make it a whole lot easier to troubleshoot!

**Comment by Zaccov** [comment] 2018-05-23 19:31
[log-2018-05-23-19.06.06.zip](https://github.com/emilsvennesson/kodi-viaplay/files/2032532/log-2018-05-23-19.06.06.zip)
Here you go

**Comment by Leatherface75** [comment] 2018-07-04 21:55
You can't stream channels if you don't have a Viasat subscription with those channels.

**Comment by Zaccov** [comment] 2018-07-05 03:13
Actually you can. At the moment you can stream channel 3, 6, 8 and 10.

**Comment by Leatherface75** [comment] 2018-07-05 13:56
No it doesn't work in app on phone atleast.

**Comment by Leatherface75** [comment] 2018-07-05 14:01
Yes it works in webbrowser but not in Android App.
I checked in a friends phone.

**Comment by Zaccov** [comment] 2018-07-05 14:03
![screenshot_20180705-155952](https://user-images.githubusercontent.com/36570678/42327793-f147c3cc-806c-11e8-91b0-60a6ed4ec7d4.jpg)
Think he needs to update app.

**Comment by Leatherface75** [comment] 2018-07-05 14:04
He can see that but not watch any channels.

**Comment by Zaccov** [comment] 2018-07-05 14:07
It's working fine on my phone

**Comment by Leatherface75** [comment] 2018-07-05 14:15
![viaplay_android](https://user-images.githubusercontent.com/2489019/42328447-8a6f6e0a-806e-11e8-8b52-c9781ed26ae6.png)

**Comment by Leatherface75** [comment] 2018-07-05 14:23
I was wrong it doesn't work in webbrowser either now.

**Comment by emilsvennesson** [comment] 2018-07-05 14:36
I have yet to recieve an informative enough post about what the problem here is. Is it the listing that doesn't work or is it the playback? Everything on my end is still working just fine, although live streams suffer from the same bug as #22.

**Comment by Zaccov** [comment] 2018-07-05 14:40
Channels not listed

**Comment by emilsvennesson** [comment] 2018-07-05 14:48
@Zaccov Can you activate your account for me so I can replicate it myself? You can hit me up on #kodi-dev at freenode (you can use the webchat at https://webchat.freenode.net/.

**Comment by Leatherface75** [comment] 2018-07-05 14:57
The problem is that you don't have permission to view it.

403 error which means "Forbidden: Access is denied".

**Comment by Zaccov** [comment] 2018-07-05 15:02
Sure

**Closed** 2018-07-05 15:19 UTC
Labels: bug

**Comment by Zaccov** [comment] 2018-07-05 15:30
Works nice using millhouse #7003 RP 3b+
